---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/matches":
    get:
      summary: Retrieves Matches
      tags:
      - Matches
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      - name: Accept
        in: header
        required: true
        schema:
          type: string
      responses:
        '200':
          description: matches found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
